Bugfix for https://github.com/sbarwe/node-red-contrib-curve/issues/1
sbarwe/node-red-contrib-curve pull request #2
Opened 2021-03-18 14:50 UTC by sdorre

2021-10-21 09:45 UTC, thkfighter approved these changes

2021-10-22 02:20 UTC, thkfighter commented
![dictionary_dropdown_at_the_right_of_function_input](https://user-images.githubusercontent.com/28823037/138382716-72cbbe6b-06f9-4a17-bf73-9077b8459ee9.png)
A dropdown list at the right of the function input box with a dictionary icon is missing.

2023-10-21 05:16 UTC, spaggi approved these changes

2023-10-21 05:16 UTC, spaggi commented
Hi, could you please please please merge this? Thank you!

2025-03-16 07:48 UTC, sbarwe requested changes
Thanks for the PR

2025-03-16 07:48 UTC, sbarwe commented on curve/curve.html
> +    <!--<input type="text" id="node-input-fexpression" autofocus="autofocus"> -->
Please remove commented html

2025-03-16 07:48 UTC, sbarwe commented on curve/curve.html
> +    <input type="text" id="node-input-fexpression" style="width:57%;" data-i18n="[placeholder]curve.placeholder.fexpression"
Is the width valid for all screensizes?

2025-03-16 09:09 UTC, merged